@startuml Class Diagram
title Class Diagram


' interface schedule
class schedule
{
	-place:string
	-date: string
	-time: string
	-group: string
	-competitors: array
	-disipline: string
	-station: string or int
	-round:string
	+CreateSchedule (): void
	+updateSchedule(): void
	+printSchedule (): void
}

class Stations
{
	-name: string
	-events: List<Event>
	+getStation(): void
}

class Groups
{
	-id: int
	-age_groups: <AGE_GROUP> enum
	-sex: <SEX_GROUP> enum
	-discipline: <DISCIPLINE> enum
	-athletes: List<Athletes>
	+generateGroups(): List<Groups>
}

class AthleteGroupAttributes
{
	-sex: <SEX_GROUP> enum
	-age: int
	-records : List<string>
	+getDisciplines(): List<DISCIPLINE>
	+getSexGroup(): AGE_GROUP
	+getAgeGroup(): SEX_GROUP

}

class Athletes
{
	-id: int
	-club: string
	-name: string
	-surname: string
}

class Event
{
	-startTime: int
	-endTime: int
	-subCompetition: SubCompetition
	+generateEvents(): List<Event>
}
class Sub_competition
{
	-id: int
	-durationMinutes: int
	-isFinal: bool
	-group: Groups
	-athletes: List<Athlete>
	+generateSubCompetition(): List<SubCompetition>

}


Athletes " 0-N "--> " 1 " Stations
Athletes --> schedule

Athletes" 1..N " --> " 1..N " Sub_competition

AthleteGroupAttributes "1" <|- " N " Athletes

Sub_competition .-> schedule
Stations "1" <-- "N" Sub_competition
Groups "1" o-- "N" Athletes
@enduml
